{
 "title": "Polygon Validator Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Network Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Checkpoint",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_checkpoint{}" }
   ]
  },
  {
   "title": "Current Block Number (ETH)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_block_number{}" }
   ]
  },
  {
   "title": "Current Performance Benchmark",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_performance_benchmark{}"
    }
   ]
  },
  { "title": "Validator Statistics [24h]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Checkpoints Missed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(checkpoints_total{range=\"total\"} - checkpoints_total{range=\"total\"} offset 24h) - on(group, job, range) group_right() (checkpoints_signed{range=\"total\"} - checkpoints_signed{range=\"total\"} offset 24h)",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Checkpoints Missed Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((checkpoints_total{range=\"total\"} - checkpoints_total{range=\"total\"} offset 24h) - on(group, job, range) group_right() (checkpoints_signed{range=\"total\"} - checkpoints_signed{range=\"total\"} offset 24h)) / on(group, job, range) group_left() (checkpoints_total{range=\"total\"} - checkpoints_total{range=\"total\"} offset 24h)",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Checkpoints Signed Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(checkpoints_signed{range=\"total\"} - checkpoints_signed{range=\"total\"} offset 24h) / on(group, job, range) group_left() (checkpoints_total{range=\"total\"} - checkpoints_total{range=\"total\"} offset 24h)",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Validator Statistics [700 checkpoints]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Checkpoints Missed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(checkpoints_total{range=\"700\"} - on(group, job, range) group_right() checkpoints_signed{range=\"700\"})",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Checkpoints Missed Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((checkpoints_total{range=\"700\"} - on(group, job, range) group_right() checkpoints_signed{range=\"700\"}) / on(group, job, range) group_left() checkpoints_total{range=\"700\"})",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Checkpoints Signed Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(checkpoints_signed{range=\"700\"} / on(group, job, range) group_left() checkpoints_total{range=\"700\"})",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Checkpoints To Performance Improvement",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "checkpoints_to_reduction", "legendFormat": "{{validator}}" }
   ]
  },
  {
   "title": "Checkpoints To Reach PB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "checkpoints_to_performance_benchmark",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  { "title": "Validator Statistics [total]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Checkpoints Missed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(checkpoints_total{range=\"total\"} - on(group, job, range) group_right() checkpoints_signed{range=\"total\"})",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Checkpoints Missed Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((checkpoints_total{range=\"total\"} - on(group, job, range) group_right() checkpoints_signed{range=\"total\"}) / on(group, job, range) group_left() checkpoints_total{range=\"total\"})",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Checkpoints Signed Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(checkpoints_signed{range=\"total\"} / on(group, job, range) group_left() checkpoints_total{range=\"total\"})",
     "legendFormat": "{{validator}}"
    }
   ]
  }
 ]
}